### PR TITLE
Update de_de.json

### PR DESCRIPTION
**Pull request by Lucanoria**

### CODE REVIEW

**Comment by NotRyken** [comment]
Apologies, the translation key set was outdated (31ec76f). Please update your PR with the new keys when convenient.

**Comment by Lucanoria** [comment]
Here is the Updated File, I missed the "Trigger Macro" string, my bad

**Comment by Lucanoria** [comment]
But is it right that "option.commandkeys.key.delay.individual.tooltip" string got removed completely?

**Comment by NotRyken** [comment]
Yes, it was split into `.first` and `.subsequent`

**Pull request merged**
